/* automatically generated from pulseaudio-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (pulseaudio_dialog_ui)
#endif
#ifdef __GNUC__
static const char pulseaudio_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char pulseaudio_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"3.20\"/><requires lib=\"libxfce4ui-2\" version=\"4.11\"/"
  "><object class=\"GtkImage\" id=\"image1\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"icon_name\">xfce4-pulseaudio-plugin</property></object><object clas"
  "s=\"XfceTitledDialog\" id=\"dialog\"><property name=\"can_focus\">False"
  "</property><property name=\"title\" translatable=\"yes\">PulseAudio Pan"
  "el Plugin</property><property name=\"default_width\">425</property><pro"
  "perty name=\"default_height\">525</property><property name=\"icon_name\""
  ">gtk-properties</property><property name=\"type_hint\">normal</property"
  "><child internal-child=\"vbox\"><object class=\"GtkBox\" id=\"dialog-vb"
  "ox2\"><property name=\"visible\">True</property><property name=\"can_fo"
  "cus\">False</property><property name=\"orientation\">vertical</property"
  "><property name=\"spacing\">2</property><child internal-child=\"action_"
  "area\"><object class=\"GtkButtonBox\" id=\"dialog-action_area2\"><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">False<"
  "/property><property name=\"layout_style\">end</property><child><object "
  "class=\"GtkButton\" id=\"close-button\"><property name=\"label\">gtk-cl"
  "ose</property><property name=\"visible\">True</property><property name="
  "\"can_focus\">True</property><property name=\"receives_default\">True</"
  "property><property name=\"use_stock\">True</property></object><packing>"
  "<property name=\"expand\">False</property><property name=\"fill\">False"
  "</property><property name=\"position\">0</property></packing></child><c"
  "hild><object class=\"GtkButton\" id=\"help-button\"><property name=\"la"
  "bel\">gtk-help</property><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">True</property><property name=\"receives_defau"
  "lt\">True</property><property name=\"use_stock\">True</property></objec"
  "t><packing><property name=\"expand\">False</property><property name=\"f"
  "ill\">False</property><property name=\"position\">1</property><property"
  " name=\"secondary\">True</property></packing></child></object><packing>"
  "<property name=\"expand\">False</property><property name=\"fill\">True<"
  "/property><property name=\"pack_type\">end</property><property name=\"p"
  "osition\">0</property></packing></child><child><object class=\"GtkBox\""
  " id=\"vbox1\"><property name=\"visible\">True</property><property name="
  "\"can_focus\">False</property><property name=\"border_width\">6</proper"
  "ty><property name=\"orientation\">vertical</property><property name=\"s"
  "pacing\">12</property><child><object class=\"GtkFrame\" id=\"frame1\"><"
  "property name=\"visible\">True</property><property name=\"can_focus\">F"
  "alse</property><property name=\"label_xalign\">0</property><property na"
  "me=\"shadow_type\">none</property><child><object class=\"GtkAlignment\""
  " id=\"alignment1\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">False</property><property name=\"top_padding\">6</pr"
  "operty><property name=\"left_padding\">12</property><property name=\"ri"
  "ght_padding\">12</property><child><object class=\"GtkBox\" id=\"vbox2\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"orientation\">vertical</property><pro"
  "perty name=\"spacing\">6</property><child><object class=\"GtkCheckButto"
  "n\" id=\"checkbutton-keyboard-shortcuts\"><property name=\"label\" tran"
  "slatable=\"yes\">Enable keyboard _shortcuts for volume control</propert"
  "y><property name=\"visible\">True</property><property name=\"can_focus\""
  ">True</property><property name=\"receives_default\">False</property><pr"
  "operty name=\"tooltip_text\" translatable=\"yes\">Enables volume contro"
  "l using multimedia keys. Make sure no other application that listens to"
  " these keys (e.g. xfce4-volumed) is running in the background.</propert"
  "y><property name=\"halign\">start</property><property name=\"use_underl"
  "ine\">True</property><property name=\"draw_indicator\">True</property><"
  "/object><packing><property name=\"expand\">True</property><property nam"
  "e=\"fill\">True</property><property name=\"position\">0</property></pac"
  "king></child><child><object class=\"GtkCheckButton\" id=\"checkbutton-s"
  "how-notifications\"><property name=\"label\" translatable=\"yes\">Show "
  "_notifications when volume changes</property><property name=\"visible\""
  ">True</property><property name=\"can_focus\">True</property><property n"
  "ame=\"receives_default\">False</property><property name=\"tooltip_text\""
  " translatable=\"yes\">Enables on-screen volume notifications.</property"
  "><property name=\"halign\">start</property><property name=\"use_underli"
  "ne\">True</property><property name=\"draw_indicator\">True</property></"
  "object><packing><property name=\"expand\">True</property><property name"
  "=\"fill\">True</property><property name=\"position\">1</property></pack"
  "ing></child></object></child></object></child><child type=\"label\"><ob"
  "ject class=\"GtkLabel\" id=\"label1\"><property name=\"visible\">True</"
  "property><property name=\"can_focus\">False</property><property name=\""
  "label\" translatable=\"yes\">Behaviour</property><attributes><attribute"
  " name=\"weight\" value=\"bold\"/></attributes></object></child></object"
  "><packing><property name=\"expand\">False</property><property name=\"fi"
  "ll\">True</property><property name=\"position\">0</property></packing><"
  "/child><child><object class=\"GtkFrame\" id=\"frame2\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"label_xalign\">0</property><property name=\"shadow_type"
  "\">none</property><child><object class=\"GtkAlignment\" id=\"alignment2"
  "\"><property name=\"visible\">True</property><property name=\"can_focus"
  "\">False</property><property name=\"top_padding\">6</property><property"
  " name=\"left_padding\">12</property><property name=\"right_padding\">12"
  "</property><child><object class=\"GtkGrid\"><property name=\"visible\">"
  "True</property><property name=\"can_focus\">False</property><property n"
  "ame=\"row_spacing\">6</property><property name=\"column_spacing\">12</p"
  "roperty><child><object class=\"GtkLabel\" id=\"label2\"><property name="
  "\"visible\">True</property><property name=\"can_focus\">False</property"
  "><property name=\"label\" translatable=\"yes\">Audio _Mixer</property><"
  "property name=\"use_underline\">True</property></object><packing><prope"
  "rty name=\"left_attach\">0</property><property name=\"top_attach\">0</p"
  "roperty></packing></child><child><object class=\"GtkEntry\" id=\"entry-"
  "mixer-command\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">True</property><property name=\"tooltip_text\" translat"
  "able=\"yes\">Audio mixer command that can be executed from the context "
  "menu, e.g. \"pavucontrol\", \"unity-control-center sound\".</property><"
  "property name=\"hexpand\">True</property><property name=\"invisible_cha"
  "r\">\342\200\242</property><property name=\"primary_icon_activatable\">"
  "False</property><property name=\"secondary_icon_activatable\">False</pr"
  "operty></object><packing><property name=\"left_attach\">1</property><pr"
  "operty name=\"top_attach\">0</property></packing></child><child><object"
  " class=\"GtkButton\" id=\"button-run-mixer\"><property name=\"label\" t"
  "ranslatable=\"yes\">_Run Audio Mixer...</property><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">True</property><prope"
  "rty name=\"receives_default\">True</property><property name=\"halign\">"
  "start</property><property name=\"image\">image1</property><property nam"
  "e=\"use_underline\">True</property></object><packing><property name=\"l"
  "eft_attach\">0</property><property name=\"top_attach\">1</property><pro"
  "perty name=\"width\">2</property></packing></child></object></child></o"
  "bject></child><child type=\"label\"><object class=\"GtkLabel\" id=\"lab"
  "el3\"><property name=\"visible\">True</property><property name=\"can_fo"
  "cus\">False</property><property name=\"label\" translatable=\"yes\">Sou"
  "nd settings</property><attributes><attribute name=\"weight\" value=\"bo"
  "ld\"/></attributes></object></child></object><packing><property name=\""
  "expand\">False</property><property name=\"fill\">True</property><proper"
  "ty name=\"position\">1</property></packing></child><child><object class"
  "=\"GtkFrame\" id=\"media-player-frame\"><property name=\"visible\">True"
  "</property><property name=\"can_focus\">False</property><property name="
  "\"label_xalign\">0</property><property name=\"shadow_type\">none</prope"
  "rty><child><object class=\"GtkAlignment\" id=\"alignment3\"><property n"
  "ame=\"visible\">True</property><property name=\"can_focus\">False</prop"
  "erty><property name=\"top_padding\">6</property><property name=\"left_p"
  "adding\">12</property><property name=\"right_padding\">12</property><ch"
  "ild><object class=\"GtkCheckButton\" id=\"checkbutton-mpris-support\"><"
  "property name=\"label\" translatable=\"yes\">Control playback of media "
  "players</property><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">True</property><property name=\"receives_default\">Fa"
  "lse</property><property name=\"halign\">start</property><property name="
  "\"draw_indicator\">True</property></object></child></object></child><ch"
  "ild type=\"label\"><object class=\"GtkLabel\" id=\"label4\"><property n"
  "ame=\"visible\">True</property><property name=\"can_focus\">False</prop"
  "erty><property name=\"label\" translatable=\"yes\">Media Players</prope"
  "rty><attributes><attribute name=\"weight\" value=\"bold\"/></attributes"
  "></object></child></object><packing><property name=\"expand\">False</pr"
  "operty><property name=\"fill\">True</property><property name=\"position"
  "\">2</property></packing></child></object><packing><property name=\"exp"
  "and\">False</property><property name=\"fill\">True</property><property "
  "name=\"position\">1</property></packing></child></object></child><actio"
  "n-widgets><action-widget response=\"0\">close-button</action-widget><ac"
  "tion-widget response=\"0\">help-button</action-widget></action-widgets>"
  "</object></interface>"
};

static const unsigned pulseaudio_dialog_ui_length = 9423u;

